### [[ path ]] ###
export PATH=$HOME/RandomScripts:$PATH
export PATH=/home/develeap/Desktop/workspace/scripts-collection/:$PATH
export PATH=/home/develeap/.local/bin:$PATH

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

### [aliases] ###
alias vim="nvim"
#test -f /opt/coreutils/bin/ls && alias ls="/opt/coreutils/bin/ls"
alias clip='xclip -selection clipboard'
alias tmux='tmux -u'
alias copy='xclip -selection clipboard'

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(git docker colorize command-not-found emoji fzf zsh-interactive-cd zsh-syntax-highlighting zsh-autosuggestions aws jump autojump kubectl virtualenv helm)

### [[ Auto Completion ]] ###
command -v helm &> /dev/null && source <(helm completion zsh)
command -v argocd &> /dev/null && compdef _argocd argocd && source <(argocd completion zsh)


source $ZSH/oh-my-zsh.sh
source ~/.bashrc

# Auto Jump
autoload -U compinit && compinit -u 
autoload -U compinit
compinit -i

autoload -U +X bashcompinit && bashcompinit
# complete -o nospace -C /usr/bin/terraform terraform

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# NVM auto completion
export NVM_DIR="$HOME/.nvm" || :
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" || : 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" || :  # This loads nvm bash_completion


